### ISSUE TITLE
Galaxy download failed

### ISSUE THREAD

**Issue by EugenMayer** [ElaoInfra/ansible-role-shorewall#4]
Since you do not have a master branch anymore, the galaxy download fails,

```
- downloading role from https://github.com/ElaoInfra/ansible-role-shorewall/archive/master.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found
```

**Comment by nervo** [comment]
All of ElaoInfra ansible roles are "frozen". You can find a maintain version of this role in the manala organization: https://github.com/manala/ansible-role-shorewall
